/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/User": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {
                     *       "$id": "1",
                     *       "username": "testuser",
                     *       "wishLists": {
                     *         "$id": "2",
                     *         "$values": [
                     *           {
                     *             "$id": "3",
                     *             "name": "Birthday WishList",
                     *             "isPrivate": true,
                     *             "userId": 1,
                     *             "items": {
                     *               "$id": "4",
                     *               "$values": [
                     *                 {
                     *                   "$id": "5",
                     *                   "name": "Noise-cancelling headphones",
                     *                   "description": "High-quality over-ear headphones",
                     *                   "price": 250,
                     *                   "isPurchased": false,
                     *                   "link": "https://example.com/headphones",
                     *                   "purchasedByUserId": null,
                     *                   "wishListId": 1
                     *                 }
                     *               ]
                     *             }
                     *           }
                     *         ]
                     *       }
                     *     } */
                    "application/json": components["schemas"]["UserDTO"];
                    /** @example {
                     *       "$id": "1",
                     *       "username": "testuser",
                     *       "wishLists": {
                     *         "$id": "2",
                     *         "$values": [
                     *           {
                     *             "$id": "3",
                     *             "name": "Birthday WishList",
                     *             "isPrivate": true,
                     *             "userId": 1,
                     *             "items": {
                     *               "$id": "4",
                     *               "$values": [
                     *                 {
                     *                   "$id": "5",
                     *                   "name": "Noise-cancelling headphones",
                     *                   "description": "High-quality over-ear headphones",
                     *                   "price": 250,
                     *                   "isPurchased": false,
                     *                   "link": "https://example.com/headphones",
                     *                   "purchasedByUserId": null,
                     *                   "wishListId": 1
                     *                 }
                     *               ]
                     *             }
                     *           }
                     *         ]
                     *       }
                     *     } */
                    "text/json": components["schemas"]["UserDTO"];
                    /** @example {
                     *       "$id": "1",
                     *       "username": "testuser",
                     *       "wishLists": {
                     *         "$id": "2",
                     *         "$values": [
                     *           {
                     *             "$id": "3",
                     *             "name": "Birthday WishList",
                     *             "isPrivate": true,
                     *             "userId": 1,
                     *             "items": {
                     *               "$id": "4",
                     *               "$values": [
                     *                 {
                     *                   "$id": "5",
                     *                   "name": "Noise-cancelling headphones",
                     *                   "description": "High-quality over-ear headphones",
                     *                   "price": 250,
                     *                   "isPurchased": false,
                     *                   "link": "https://example.com/headphones",
                     *                   "purchasedByUserId": null,
                     *                   "wishListId": 1
                     *                 }
                     *               ]
                     *             }
                     *           }
                     *         ]
                     *       }
                     *     } */
                    "application/*+json": components["schemas"]["UserDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["User"];
                        "application/json": components["schemas"]["User"];
                        "text/json": components["schemas"]["User"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/User/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["User"];
                        "application/json": components["schemas"]["User"];
                        "text/json": components["schemas"]["User"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/User/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WishListItemDTO"][];
                        "application/json": components["schemas"]["WishListItemDTO"][];
                        "text/json": components["schemas"]["WishListItemDTO"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/WishList": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {
                     *       "$id": "1",
                     *       "name": "Birthday WishList",
                     *       "isPrivate": true,
                     *       "userId": 1,
                     *       "items": {
                     *         "$id": "2",
                     *         "$values": [
                     *           {
                     *             "$id": "3",
                     *             "name": "Noise-cancelling headphones",
                     *             "description": "High-quality over-ear headphones",
                     *             "price": 250,
                     *             "isPurchased": false,
                     *             "link": "https://example.com/headphones",
                     *             "purchasedByUserId": 1,
                     *             "wishListId": 1
                     *           }
                     *         ]
                     *       }
                     *     } */
                    "application/json": components["schemas"]["WishListDTO"];
                    /** @example {
                     *       "$id": "1",
                     *       "name": "Birthday WishList",
                     *       "isPrivate": true,
                     *       "userId": 1,
                     *       "items": {
                     *         "$id": "2",
                     *         "$values": [
                     *           {
                     *             "$id": "3",
                     *             "name": "Noise-cancelling headphones",
                     *             "description": "High-quality over-ear headphones",
                     *             "price": 250,
                     *             "isPurchased": false,
                     *             "link": "https://example.com/headphones",
                     *             "purchasedByUserId": 1,
                     *             "wishListId": 1
                     *           }
                     *         ]
                     *       }
                     *     } */
                    "text/json": components["schemas"]["WishListDTO"];
                    /** @example {
                     *       "$id": "1",
                     *       "name": "Birthday WishList",
                     *       "isPrivate": true,
                     *       "userId": 1,
                     *       "items": {
                     *         "$id": "2",
                     *         "$values": [
                     *           {
                     *             "$id": "3",
                     *             "name": "Noise-cancelling headphones",
                     *             "description": "High-quality over-ear headphones",
                     *             "price": 250,
                     *             "isPurchased": false,
                     *             "link": "https://example.com/headphones",
                     *             "purchasedByUserId": 1,
                     *             "wishListId": 1
                     *           }
                     *         ]
                     *       }
                     *     } */
                    "application/*+json": components["schemas"]["WishListDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WishList"];
                        "application/json": components["schemas"]["WishList"];
                        "text/json": components["schemas"]["WishList"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/WishList/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WishListDTO"];
                        "application/json": components["schemas"]["WishListDTO"];
                        "text/json": components["schemas"]["WishListDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/WishList/{wishListId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wishListId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WishListItemDTO"][];
                        "application/json": components["schemas"]["WishListItemDTO"][];
                        "text/json": components["schemas"]["WishListItemDTO"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/WishListItem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {
                     *       "$id": "1",
                     *       "name": "Toy Car",
                     *       "description": "A red toy car for kids",
                     *       "price": 20.99,
                     *       "isPurchased": false,
                     *       "link": "http://example.com/toycar",
                     *       "purchasedByUserId": null,
                     *       "wishListId": 1
                     *     } */
                    "application/json": components["schemas"]["WishListItemDTO"];
                    /** @example {
                     *       "$id": "1",
                     *       "name": "Toy Car",
                     *       "description": "A red toy car for kids",
                     *       "price": 20.99,
                     *       "isPurchased": false,
                     *       "link": "http://example.com/toycar",
                     *       "purchasedByUserId": null,
                     *       "wishListId": 1
                     *     } */
                    "text/json": components["schemas"]["WishListItemDTO"];
                    /** @example {
                     *       "$id": "1",
                     *       "name": "Toy Car",
                     *       "description": "A red toy car for kids",
                     *       "price": 20.99,
                     *       "isPurchased": false,
                     *       "link": "http://example.com/toycar",
                     *       "purchasedByUserId": null,
                     *       "wishListId": 1
                     *     } */
                    "application/*+json": components["schemas"]["WishListItemDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WishListItemDTO"];
                        "application/json": components["schemas"]["WishListItemDTO"];
                        "text/json": components["schemas"]["WishListItemDTO"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/WishListItem/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {
                     *       "$id": "1",
                     *       "name": "Toy Car",
                     *       "description": "A red toy car for kids",
                     *       "price": 20.99,
                     *       "isPurchased": false,
                     *       "link": "http://example.com/toycar",
                     *       "purchasedByUserId": null,
                     *       "wishListId": 1
                     *     } */
                    "application/json": components["schemas"]["WishListItemDTO"];
                    /** @example {
                     *       "$id": "1",
                     *       "name": "Toy Car",
                     *       "description": "A red toy car for kids",
                     *       "price": 20.99,
                     *       "isPurchased": false,
                     *       "link": "http://example.com/toycar",
                     *       "purchasedByUserId": null,
                     *       "wishListId": 1
                     *     } */
                    "text/json": components["schemas"]["WishListItemDTO"];
                    /** @example {
                     *       "$id": "1",
                     *       "name": "Toy Car",
                     *       "description": "A red toy car for kids",
                     *       "price": 20.99,
                     *       "isPurchased": false,
                     *       "link": "http://example.com/toycar",
                     *       "purchasedByUserId": null,
                     *       "wishListId": 1
                     *     } */
                    "application/*+json": components["schemas"]["WishListItemDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/WishListItem/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {
                     *       "$id": "1",
                     *       "wishListItemId": 1,
                     *       "userId": 2
                     *     } */
                    "application/json": components["schemas"]["PurchaseRequestDTO"];
                    /** @example {
                     *       "$id": "1",
                     *       "wishListItemId": 1,
                     *       "userId": 2
                     *     } */
                    "text/json": components["schemas"]["PurchaseRequestDTO"];
                    /** @example {
                     *       "$id": "1",
                     *       "wishListItemId": 1,
                     *       "userId": 2
                     *     } */
                    "application/*+json": components["schemas"]["PurchaseRequestDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        PurchaseRequestDTO: {
            /** Format: int32 */
            wishListItemId?: number;
            /** Format: int32 */
            userId?: number;
        };
        User: {
            /** Format: int32 */
            userId?: number;
            username: string | null;
            wishLists?: components["schemas"]["WishList"][] | null;
            purchasedItems?: components["schemas"]["WishListItem"][] | null;
        };
        UserDTO: {
            username: string | null;
            wishLists?: components["schemas"]["WishListDTO"][] | null;
        };
        WishList: {
            /** Format: int32 */
            wishListId?: number;
            name: string | null;
            isPrivate?: boolean;
            /** Format: int32 */
            userId?: number;
            user: components["schemas"]["User"];
            items?: components["schemas"]["WishListItem"][] | null;
        };
        WishListDTO: {
            name: string;
            isPrivate?: boolean;
            /** Format: int32 */
            userId: number;
            items?: components["schemas"]["WishListItemDTO"][] | null;
        };
        WishListItem: {
            /** Format: int32 */
            itemId?: number;
            name: string | null;
            description: string | null;
            /** Format: double */
            price?: number;
            isPurchased?: boolean;
            /** Format: int32 */
            wishListId?: number;
            link: string | null;
            wishList: components["schemas"]["WishList"];
            /** Format: int32 */
            purchasedByUserId?: number | null;
            purchasedBy?: components["schemas"]["User"];
        };
        WishListItemDTO: {
            name: string;
            description: string;
            /** Format: double */
            price?: number;
            isPurchased?: boolean;
            link: string;
            /** Format: int32 */
            purchasedByUserId?: number | null;
            /** Format: int32 */
            wishListId: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
