/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileProfileRouteImport } from './routes/Profile/ProfileRoute'
import { Route as NotificationsNotificationRouteImport } from './routes/Notifications/NotificationRoute'
import { Route as HomeHomeRouteImport } from './routes/Home/HomeRoute'
import { Route as DashboardDashboardRouteImport } from './routes/Dashboard/DashboardRoute'
import { Route as AddEmployeeAddEmployeeRouteImport } from './routes/AddEmployee/AddEmployeeRoute'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileProfileRouteRoute = ProfileProfileRouteImport.update({
  id: '/Profile/ProfileRoute',
  path: '/Profile/ProfileRoute',
  getParentRoute: () => rootRoute,
} as any)

const NotificationsNotificationRouteRoute =
  NotificationsNotificationRouteImport.update({
    id: '/Notifications/NotificationRoute',
    path: '/Notifications/NotificationRoute',
    getParentRoute: () => rootRoute,
  } as any)

const HomeHomeRouteRoute = HomeHomeRouteImport.update({
  id: '/Home/HomeRoute',
  path: '/Home/HomeRoute',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashboardRouteRoute = DashboardDashboardRouteImport.update({
  id: '/Dashboard/DashboardRoute',
  path: '/Dashboard/DashboardRoute',
  getParentRoute: () => rootRoute,
} as any)

const AddEmployeeAddEmployeeRouteRoute =
  AddEmployeeAddEmployeeRouteImport.update({
    id: '/AddEmployee/AddEmployeeRoute',
    path: '/AddEmployee/AddEmployeeRoute',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/AddEmployee/AddEmployeeRoute': {
      id: '/AddEmployee/AddEmployeeRoute'
      path: '/AddEmployee/AddEmployeeRoute'
      fullPath: '/AddEmployee/AddEmployeeRoute'
      preLoaderRoute: typeof AddEmployeeAddEmployeeRouteImport
      parentRoute: typeof rootRoute
    }
    '/Dashboard/DashboardRoute': {
      id: '/Dashboard/DashboardRoute'
      path: '/Dashboard/DashboardRoute'
      fullPath: '/Dashboard/DashboardRoute'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/Home/HomeRoute': {
      id: '/Home/HomeRoute'
      path: '/Home/HomeRoute'
      fullPath: '/Home/HomeRoute'
      preLoaderRoute: typeof HomeHomeRouteImport
      parentRoute: typeof rootRoute
    }
    '/Notifications/NotificationRoute': {
      id: '/Notifications/NotificationRoute'
      path: '/Notifications/NotificationRoute'
      fullPath: '/Notifications/NotificationRoute'
      preLoaderRoute: typeof NotificationsNotificationRouteImport
      parentRoute: typeof rootRoute
    }
    '/Profile/ProfileRoute': {
      id: '/Profile/ProfileRoute'
      path: '/Profile/ProfileRoute'
      fullPath: '/Profile/ProfileRoute'
      preLoaderRoute: typeof ProfileProfileRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AddEmployee/AddEmployeeRoute': typeof AddEmployeeAddEmployeeRouteRoute
  '/Dashboard/DashboardRoute': typeof DashboardDashboardRouteRoute
  '/Home/HomeRoute': typeof HomeHomeRouteRoute
  '/Notifications/NotificationRoute': typeof NotificationsNotificationRouteRoute
  '/Profile/ProfileRoute': typeof ProfileProfileRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AddEmployee/AddEmployeeRoute': typeof AddEmployeeAddEmployeeRouteRoute
  '/Dashboard/DashboardRoute': typeof DashboardDashboardRouteRoute
  '/Home/HomeRoute': typeof HomeHomeRouteRoute
  '/Notifications/NotificationRoute': typeof NotificationsNotificationRouteRoute
  '/Profile/ProfileRoute': typeof ProfileProfileRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/AddEmployee/AddEmployeeRoute': typeof AddEmployeeAddEmployeeRouteRoute
  '/Dashboard/DashboardRoute': typeof DashboardDashboardRouteRoute
  '/Home/HomeRoute': typeof HomeHomeRouteRoute
  '/Notifications/NotificationRoute': typeof NotificationsNotificationRouteRoute
  '/Profile/ProfileRoute': typeof ProfileProfileRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AddEmployee/AddEmployeeRoute'
    | '/Dashboard/DashboardRoute'
    | '/Home/HomeRoute'
    | '/Notifications/NotificationRoute'
    | '/Profile/ProfileRoute'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AddEmployee/AddEmployeeRoute'
    | '/Dashboard/DashboardRoute'
    | '/Home/HomeRoute'
    | '/Notifications/NotificationRoute'
    | '/Profile/ProfileRoute'
  id:
    | '__root__'
    | '/'
    | '/AddEmployee/AddEmployeeRoute'
    | '/Dashboard/DashboardRoute'
    | '/Home/HomeRoute'
    | '/Notifications/NotificationRoute'
    | '/Profile/ProfileRoute'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddEmployeeAddEmployeeRouteRoute: typeof AddEmployeeAddEmployeeRouteRoute
  DashboardDashboardRouteRoute: typeof DashboardDashboardRouteRoute
  HomeHomeRouteRoute: typeof HomeHomeRouteRoute
  NotificationsNotificationRouteRoute: typeof NotificationsNotificationRouteRoute
  ProfileProfileRouteRoute: typeof ProfileProfileRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddEmployeeAddEmployeeRouteRoute: AddEmployeeAddEmployeeRouteRoute,
  DashboardDashboardRouteRoute: DashboardDashboardRouteRoute,
  HomeHomeRouteRoute: HomeHomeRouteRoute,
  NotificationsNotificationRouteRoute: NotificationsNotificationRouteRoute,
  ProfileProfileRouteRoute: ProfileProfileRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/AddEmployee/AddEmployeeRoute",
        "/Dashboard/DashboardRoute",
        "/Home/HomeRoute",
        "/Notifications/NotificationRoute",
        "/Profile/ProfileRoute"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/AddEmployee/AddEmployeeRoute": {
      "filePath": "AddEmployee/AddEmployeeRoute.tsx"
    },
    "/Dashboard/DashboardRoute": {
      "filePath": "Dashboard/DashboardRoute.tsx"
    },
    "/Home/HomeRoute": {
      "filePath": "Home/HomeRoute.tsx"
    },
    "/Notifications/NotificationRoute": {
      "filePath": "Notifications/NotificationRoute.tsx"
    },
    "/Profile/ProfileRoute": {
      "filePath": "Profile/ProfileRoute.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
